# AAK-Test/django_task_api/tasks/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, LabelViewSet, UserRegistrationView

# Create a DefaultRouter instance.
# DefaultRouter automatically generates URL patterns for standard RESTful operations (CRUD)
# based on Django REST Framework's ViewSets.
router = DefaultRouter()

# Register TaskViewSet with the router.
# This will generate URLs like:
# - /tasks/ (for listing tasks and creating new ones)
# - /tasks/{id}/ (for retrieving, updating, and deleting specific tasks)
router.register(r'tasks', TaskViewSet)

# Register LabelViewSet with the router.
# This will generate URLs like:
# - /labels/ (for listing labels and creating new ones)
# - /labels/{id}/ (for retrieving, updating, and deleting specific labels)
router.register(r'labels', LabelViewSet)

# Define the URL patterns for the 'tasks' application.
urlpatterns = [
    # Include the URLs generated by the router.
    # This incorporates all the CRUD endpoints for tasks and labels under the base path.
    path('', include(router.urls)),

    # Define a specific URL pattern for user registration.
    # Requests to '/register/' will be handled by the UserRegistrationView.
    # `name='user-register'` provides a reverse lookup name for this URL.
    path('register/', UserRegistrationView.as_view(), name='user-register'),
]